#!/bin/bash
#set -u;
## TODO find more elegant solution to the following line

## variable initialisation, can be overwritten in config.
## IDEA replace varinit in script with default conf?

export CONFIG="/var/lib/aide/aide.conf.autogenerated";
export AIDEBIN="/usr/bin/aide";

if ! [ -x "/usr/bin/aide" ]; then
  export AIDEBIN="/usr/sbin/aide";
fi


## check if user's config exists, and if so, overwrites default variables
if [ -f "$HOME/.swaiderc" ]; then
  source "$HOME/.swaiderc";
fi


source ./swaide.functions;
case $1 in
  --init|-i)
          init;
          ;;
  --check|-c)
          check;
          ;;
  --check-config|-k)
          checkconfig "$2";
          ;;
  --update-config|-U)
          updateconfig "$2";
          ;;
  --update-db|--update-database|-u)
          updatedb;
          ;;
  --help|-h)
	        swhelp;
	  ;;
  *)
          echo "Unknown option/error";
	  swhelp;
          ;;
esac;
exit;
