#!/bin/bash
set -u
## TODO find more elegant solution to the following line
source ./swaide.functions

## variable initialisation, can be overwritten in config.
## IDEA replace varinit in script with default conf?

#RET=0
CONFIG="/var/lib/aide/aide.conf.autogenerated"
AIDEBIN="/usr/sbin/aide"

if ! [ -x "/usr/bin/aide" ]; then
  AIDEBIN="/usr/sbin/aide"
fi


## check if user's config exists, and if so, overwrites default variables
if [ -f "$HOME/.swaiderc" ]; then
  source ~/.swaiderc
fi


case "$1" in
  --init|-i)
          init
          ;;
  --check|-c)
          check;
          ;;
  --check-config|-k)
          checkconfig;
          ;;
  --update-config|-U)
          updateconfig;
          ;;
  --update-db|--update-database|-u)
          updatedb;
          ;;
  --help|-h|*)
          swhelp;
          ;;
esac
exit $RET;
